### ISSUE TITLE
bug: App force close when opening

### ISSUE THREAD

**Issue by kazimmt** [LeddaZ/ReVancedUpdater#11]
## Issue
Whenever I try to Open ReVanced Updater, It crashes

## Device info
Device: Poco F3
Android: 13
Rom: Crdroid 9.7

## Log
```
time: 1689758208716
msg: java.lang.IllegalArgumentException: Invalid version format
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{it.leddaz.revancedupdater/it.leddaz.revancedupdater.MainActivity}: java.lang.IllegalArgumentException: Invalid version format
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3791)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7930)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
Caused by: java.lang.IllegalArgumentException: Invalid version format
	at it.leddaz.revancedupdater.utils.misc.Version.setVersion(Version.java:39)
	at it.leddaz.revancedupdater.utils.misc.Utils.getAppVersion(Utils.kt:96)
	at it.leddaz.revancedupdater.MainActivity.getVersions(MainActivity.kt:148)
	at it.leddaz.revancedupdater.MainActivity.refresh(MainActivity.kt:263)
	at it.leddaz.revancedupdater.MainActivity.onCreate(MainActivity.kt:58)
	at android.app.Activity.performCreate(Activity.java:8360)
	at android.app.Activity.performCreate(Activity.java:8339)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
	... 12 more
```

**Comment by LeddaZ** [comment]
It seems that the app can't read the installed microG's version. Try to uninstall Vanced microG if you already have it, then download it from the app.

**Comment by kazimmt** [comment]
> It seems that the app can't read the installed microG's version. Try to uninstall Vanced microG if you already have it, then download it from the app.

Thanks. Issue Resolve

**Comment by kazimmt** [comment]
It should show a toast to install correct microg or something
